version: "3"
services:
  php:
    container_name: ${PROJECT_NAME}_php
    image: ${PROJECT_NAME}_php
    restart: on-failure
    build:
      context: ./php
      args:
        PHP_VERSION: ${PHP_VERSION}
    tty: true
    env_file:
      - ./.env
    volumes:
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ..:/var/www/html
    depends_on:
      - mysql
  web:
    container_name: ${PROJECT_NAME}_web
    image: ${PROJECT_NAME}_web
    build: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ..:/var/www/html
    depends_on:
      - php
    restart: on-failure
    env_file:
      - ./.env
  mysql:
    container_name: ${PROJECT_NAME}_mysql
    image: mysql:${MYSQL_VERSION}
    restart: on-failure
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - "./data/mysql:/var/lib/mysql"
